/* Modelagem Básica 
ENTIDADE = TABELA
CAMPOS = ATRIBUTOS */

CLIENTE

NOME - CARACTER(30)
CPF - NUMERICO(11)
EMAIL - CARACTER(30)
TELEFONE - CARACTER(30)
ENDERECO - CARACTER(100)
SEXO - CARACTER(1)

/* PROCESSOS DE MODELAGEM */

/* FASE 1 E FASE 2 - AO ADM DE DADOS */
MODELAGEM CONCEITUAL - RASCUNHO EM PAPEL
MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM

/* FASE 3 - DBA / ADM */
MODELAGEM FÍSICA - SRIPTS DE BANCO

/* INCIANDO A MODELAGEM FISICA */
/* CRIANDO O BANCO DE DADOS */
CREATE DATABASE PROJETO;

/* CONECTANDO AO BANCO DE DADOS */
USE PROJETO;

/* CRIANDO A TABELA DE CLIENTES */
CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
);

/* VERIFICANDO AS TABELAS DO BANCO DE DADOS */

SHOW TABLES;

/* DESCOBRINDO ESTRUTURA DA TABELA */

DESC CLIENTE;

/* SINTAXE BASICA PARA INSERÇÃO
INSERT INTO TABELA... */

/* FORMA 1 - OMITINDO AS COLUNAS */
INSERT INTO CLIENTE VALUES('JOAO','M','JOAO@GMAIL.COM',988638273,'22923110','MAIA LACERDA - ESTACIO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES('CELIA','F','CELIA@HOTMAIL.COM',541521456,'25078869','RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES('JORGE','M',NULL,885755896,'58748895','OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');

/* FORMA 2 - COLOCANDO AS COLUNAS */
INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('LILIAN','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','947785696',887774856);

/* FORMA 3 - INSERT COMPACTO - SOMENTE MYSQL */
INSERT INTO CLIENTE VALUES('ANA','F','ANA@GMAIL.COM',85548962,'548556985','PRES ANTONIO 
CARLOS - CENTRO - SAO PAULO - SP'),
							('CARLA','F','CARLA@TERATI.COM.BR',7745828,'66587458','SAMUEL SILVA 
							- CENTRO - BELO HORIZONTE - MG');

INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('ALF','M','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','991061504',31748861808);

/* COMANDO SELECT 
SELEÇÃO PROJEÇÃO E JUNÇÃO.
*/

SELECT NOW();

SELECT 'FELIPE MAFRA';

SELECT 'BANCO DE DADOS';

/* ALIAS DE COLUNAS */

SELECT NOME, SEXO, EMAIL FROM CLIENTE;
SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;
SELECT NOME, SEXO, EMAIL, ENDERECO, NOW() AS DATA_HORA FROM CLIENTE;
/* APENAS PARA FINS ACADEMICOS */
/* COMANDO QUE TRAZ TODA AS INFORMAÇÕES DA TABELA */
/* ESSE COMANDO CARREGA O PROCESSAMENTO DE DADOS DO BANCO, PROCESSAR SOMENTE A INFORMAÇÃO QUE O USUARIO DESEJA */
SELECT * FROM CLIENTE;

/* FILTRANDO DADOS COOM WHERE E LIKE */

SELECT * FROM CLIENTE;

/* FILTRAR POR COLUNA = PROJEÇÃO */
/* FILTRO FUNCIONA POR NIVEL DE LINHA */ 
/* SELEÇÃO USA O NOME 'WHERE' */

SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = 'M';

SELECT NOME, ENDERECO FROM CLIENTE
WHERE SEXO = 'F';

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO = 'RJ';

/* UTILIZANDO O LIKE */

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE 'RJ';

/* CARACTER CORINGA % => CARACTER CORINGA */
SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE 'OSCAR CURY%';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE '%CENTRO%';

/* OPERADORES LOGICOS */

/*

TABELA DA VERDADE AND

A	B	A_OR_B	A_AND_B
0	0	   0	   0
0	1	   1       0
1	0	   1	   0 
1	1	   1       1

COMANDOS DE OPERAÇÃO LOGICOS
COMANDO = OR
COMANDO = AND

2^n | onde n => é a quantidade de variaveis

*/

SHOW DATABASE;
SELECT * FROM CLIENTE;

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE SEXO = 'M' OR ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE SEXO = 'M' AND ENDERECO LIKE '%RJ';

/* TABELA DA VERDADE = MATEMATICA DISCRETA */

/* CONTANDO OS REGISTROS DE UMA TABELA */

SELECT COUNT(*) FROM CLIENTE;

SELECT COUNT(*)
FROM CLIENTE;

/* OPERADOR GROUP BY */
SELECT SEXO, COUNT(*)
FROM CLIENTE GROUP BY SEXO;

/* PERFORMANCE EM OPERADORES LOGICOS 

PARA CONTAR
SELECT COUNT(*) FROM CLIENTE;

SELECT SEXO, COUNT(*) FROM CLIENTE
GROUP BY SEXO;

SELECT CIDADE, COUNT(*) FROM CLIENTE
GROUP BY CIDADE;

CONDIÇÃO
SEXO = F
CIDADE = RIO DE JANEIRO

SITUAÇÃO - TRATANDO COM OU / OR
70% MULHERES = SEXO = F
30% MORA NO RIO DE JANEIRO

SELECT NOME, SEXO, ENDEREÇO
FROM CLIENTE
WHERE SEXO = 'F'
OR CIDADE = 'RIO DE JANEIRO';

SITUAÇÃO - TRATANDO COM E / AND
70% MULHERES = SEXO = 'F'
30% MORA NO RIO DE JANEIRO

SELECT NOME, SEXO, ENDEREÇO
FROM CLIENTE
WHERE CIDADE = 'RIO DE JANEIRO'
AND SEXO = 'F';
*/
